delete from TB_DOMI;

INSERT INTO TB_DOMI (CD_DOMI, NM_DOMI) 
VALUES (4.0, 'Município');

INSERT INTO TB_DOMI (CD_DOMI, NM_DOMI) 
VALUES (1.0, 'Sexo');

INSERT INTO TB_DOMI (CD_DOMI, NM_DOMI) 
VALUES (2.0, 'Profissão');

INSERT INTO TB_DOMI (CD_DOMI, NM_DOMI) 
VALUES (3.0, 'Estado Civil');

INSERT INTO TB_DOMI (CD_DOMI, NM_DOMI) 
VALUES (5.0, 'UF');

INSERT INTO TB_DOMI (CD_DOMI, NM_DOMI) 
VALUES (6.0, 'Canal');

INSERT INTO TB_DOMI (CD_DOMI, NM_DOMI) 
VALUES (7.0, 'Segmento');

INSERT INTO TB_DOMI (CD_DOMI, NM_DOMI) 
VALUES (8.0, 'Ramo');

INSERT INTO TB_DOMI (CD_DOMI, NM_DOMI) 
VALUES (9.0, 'Plano');

INSERT INTO TB_DOMI (CD_DOMI, NM_DOMI) 
VALUES (10.0, 'Seguradora');

INSERT INTO TB_DOMI (CD_DOMI, NM_DOMI) 
VALUES (11.0, 'Perguntas Obrigatórias');

INSERT INTO TB_DOMI (CD_DOMI, NM_DOMI) 
VALUES (12.0, 'Tipo Pessoa');

commit;